Feature/flask
glebmiller/ru-study-python pull request #5
Opened 2022-09-20 08:10 UTC by glebmiller

2022-09-24 12:09 UTC, aleksandr-semenov-dbp requested changes

2022-09-24 12:09 UTC, aleksandr-semenov-dbp commented on exercises/flask.py
> +            if request.method == "PATCH":
Раз уж в GET мы отрабатываем 404, надо ввести проверки и в PATCH/DELETE

2022-09-26 17:27 UTC, glebmiller commented on exercises/flask.py
> +            if request.method == "PATCH":
updated

2022-10-04 09:25 UTC, aleksandr-semenov-dbp approved these changes

2022-10-04 12:23 UTC, merged